<a href="https://colab.research.google.com/github/al-imran-sonet/Learning_PyTorch/blob/main/Indexing_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Indexing (selecting data from tensors )
indexing with PyTorch is similar to indexing in NumPy

In [2]:
import torch

In [3]:
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
# lets index
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
x[0,0] # or we can doo that x[0][0]

tensor([1, 2, 3])

In [8]:
#x[0,0,0] or
x[0][0][0]

tensor(1)

In [10]:
# we can use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [11]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [12]:
# get all values of 0 th dimension but only 1 index value of 1st and 2nd dimention
x[:,1,1] # this and x[0,1,1] are not similar . in this we will not get any angle bracket


tensor([5])

In [13]:
# get index 0 of 0th and 1 st dimension and all values of 2 nd dimention
x[0,0,:]

tensor([1, 2, 3])

In [15]:
# practice return 9 , return 3,6,9

x[0,2,2],x[0,:,2]


(tensor(9), tensor([3, 6, 9]))