<a href="https://colab.research.google.com/github/al-imran-sonet/Learning_PyTorch/blob/main/Indexing_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Indexing (selecting data from tensors )
indexing with PyTorch is similar to indexing in NumPy

In [2]:
import torch

In [3]:
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
# lets index
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
x[0,0] # or we can doo that x[0][0]

tensor([1, 2, 3])

In [8]:
#x[0,0,0] or
x[0][0][0]

tensor(1)

In [10]:
# we can use ":" to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])