<a href="https://colab.research.google.com/github/al-imran-sonet/Learning_PyTorch/blob/main/Manipulating_Tensors05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Manipulating Tensors (Tensors Operations)
    1.Addition
    2.Subtraction
    3.Multiplication (element wise)
    4.Division
    5.Matrix multiplication

In [2]:
import torch

In [ ]:
# Creating a tensor
tensor1=torch.tensor([1,2,3])
tensor1=tensor1+100 # adding a particular number to a tensor
tensor1


tensor([101, 102, 103])

In [ ]:
tensor1=tensor1-100 # subtracting a particular number to a tensor
tensor1

tensor([1, 2, 3])

In [ ]:
tensor1=tensor1*10 # multiplying a number to the tensor
tensor1

tensor([10, 20, 30])

In [ ]:
##tensor1=tensor1/10 # deviding a number
tensor1

tensor([10, 20, 30])

In [ ]:
# PyTorch build in function
torch.mul(tensor1,10) # multiplication
tensor1


tensor([ 90, 100, 110])

In [ ]:
tensor1=torch.add(tensor1,20) # addition
tensor1


tensor([110, 120, 130])

### Matrix Multiplication
    Matrix Multiplication is most common operation .
    1.Dot Multiply
    2.Crose Multiply


In [ ]:
# creating tensor
tensor2 = torch.tensor([2,3,4])
tensor2

tensor([2, 3, 4])

In [ ]:
# Dot multiplication
torch.matmul(tensor2,tensor2)

tensor(29)

In [ ]:
# Dot multiplication by hand
2*2+3*3+4*4

29

In [ ]:
# time of execution
%%time

value =0
lenght=len(tensor2)
for i in range(lenght):
  value+=tensor2[i]*tensor2[i]

value
# The execution time is around 1ms to 3ms

CPU times: user 2.04 ms, sys: 0 ns, total: 2.04 ms
Wall time: 1.71 ms


tensor(29)

In [ ]:
%%time
tensor2_dot=torch.matmul(tensor2,tensor2)
tensor2_dot
# the execution time is around 400 to 800 micro sec

CPU times: user 0 ns, sys: 686 µs, total: 686 µs
Wall time: 503 µs


tensor(29)

### One of the most common error and rules that need to be satisfy for matrix multiplication
    1.The **inner dimension** must match
       example : a. (3,2) dot (3,2) --- wont work
                 b. (2,3) dot (3,2) --- will work
                 c. (3,2) dot (2,3) --- will work

    2.The resulting  matrix has same outer dimention
       example: a.(2,3) dot (3,2)-- (2,2)
                b.(3,2) dot (2,3)-- (3,3)

In [ ]:
##torch.matmul(torch.rand(3,2),torch.rand(3,2)) it will show error

torch.matmul(torch.rand(3,2),torch.rand(2,1)) #  the dimention will have to be like this tensor[m,n] and tensor[n,p] ( n is the inner dimention )

tensor([[0.7733],
        [0.1350],
        [0.4379]])

### One of the most common error is shape error
    Some time we use manipulate the shape of tensor to avoide the shape error.
    We use Transpose to switch the axis of a defined tensor .

In [3]:
#shapes for matrix multiplication
tensor_A =torch.tensor([[1,2],
                        [2,3],
                        [4,5]])
tensor_B =torch.tensor([[11,22],
                        [33,44],
                        [55,66]])
torch.matmul(tensor_A,tensor_B) # torch.mm(tensor_A,tensor_B) dose the same as the code used befor
# it will show an error because the inner dimention isnt match

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [4]:
# transpose of a matrix .
tensor_B.T,tensor_B

(tensor([[11, 33, 55],
         [22, 44, 66]]),
 tensor([[11, 22],
         [33, 44],
         [55, 66]]))

In [13]:
tensor_B=tensor_B.T
tensor_B,tensor_B.shape


(tensor([[11, 33, 55],
         [22, 44, 66]]),
 torch.Size([2, 3]))

In [15]:
tensor_R=torch.mm(tensor_A,tensor_B)
tensor_R

tensor([[ 55, 121, 187],
        [ 88, 198, 308],
        [154, 352, 550]])