<a href="https://colab.research.google.com/github/al-imran-sonet/Learning_PyTorch/blob/main/PyTorch04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor datatypes

We get 3 big errors for dataType in PyTorch and deep learning

1.Tensor not right datatype

2.Tensor not right shape

3.Tensor not on right device

-->>read_about{precision in computing, device ,requires_grad}


In [2]:
import torch

In [5]:
# Floate 32 tensor
float_32_tensor=torch.tensor([3.0,1.2,4.3],
                             dtype = None) # If we put None it will creat float 32 by default .
float_32_tensor

tensor([3.0000, 1.2000, 4.3000])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Floate 16 tensor
float_16_tensor=torch.tensor([3.0,1.2,4.3],
                             dtype = torch.float16) # If we put torch.float16 it will creat float 16.
float_16_tensor

tensor([3.0000, 1.2002, 4.3008], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
# Floate 32 tensor
float_32_tensor1=torch.tensor([3.0,1.2,4.3],
                             dtype = None, # What data type I want (float 16, float32 etc )
                              device=None, # We can change the device like cpu or gpu (like cuda)
                              requires_grad=False) # Whether or not to track gradinets with this tensors operations
float_32_tensor1

tensor([3.0000, 1.2000, 4.3000])

In [ ]:
float_32_tensor1*float_16_tensor

tensor([ 9.0000,  1.4402, 18.4934])

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9.0000,  1.4402, 18.4934])

In [3]:
int_32_tensor= torch.tensor([1,2,3],dtype= torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [6]:
float_32_tensor*int_32_tensor

tensor([ 3.0000,  2.4000, 12.9000])