<a href="https://colab.research.google.com/github/al-imran-sonet/Learning_PyTorch/blob/main/PyTorch04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor datatypes

We get 3 big errors for dataType in PyTorch and deep learning

1.Tensor not right datatype

2.Tensor not right shape

3.Tensor not on right device

-->>read_about{precision in computing, device ,requires_grad}


In [2]:
import torch

In [5]:
# Floate 32 tensor
float_32_tensor=torch.tensor([3.0,1.2,4.3],
                             dtype = None) # If we put None it will creat float 32 by default .
float_32_tensor

tensor([3.0000, 1.2000, 4.3000])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Floate 16 tensor
float_16_tensor=torch.tensor([3.0,1.2,4.3],
                             dtype = torch.float16) # If we put torch.float16 it will creat float 16.
float_16_tensor

tensor([3.0000, 1.2002, 4.3008], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
# Floate 32 tensor
float_32_tensor1=torch.tensor([3.0,1.2,4.3],
                             dtype = None, # What data type I want (float 16, float32 etc )
                              device=None, # We can change the device like cpu or gpu (like cuda)
                              requires_grad=False) # Whether or not to track gradinets with this tensors operations
float_32_tensor1

tensor([3.0000, 1.2000, 4.3000])

In [ ]:
float_32_tensor1*float_16_tensor

tensor([ 9.0000,  1.4402, 18.4934])

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9.0000,  1.4402, 18.4934])

In [13]:
int_32_tensor= torch.tensor([1,2,3],dtype= torch.Shortint) # it will show error
int_32_tensor

AttributeError: module 'torch' has no attribute 'Shortint'

In [6]:
float_32_tensor*int_32_tensor

tensor([ 3.0000,  2.4000, 12.9000])

### How to get informatino
    1.Find data type -(tensor.dtype)
    2.Find shape -(tensor.shape)
    3.Find device -(tensor.device)

In [8]:
#creating a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0796, 0.7563, 0.4322, 0.7090],
        [0.5381, 0.8500, 0.0941, 0.4752],
        [0.4227, 0.4377, 0.6341, 0.2194]])

In [12]:
# find details of the tensor
# we are using tensor attribute not function like "tensor.size() or tensor.shape()"
print(some_tensor)
print(f"Data type of the tensor {some_tensor.dtype}")
print(f"Shape of the tensor  ",some_tensor.shape)
print(f"Device the tensor is ranning ",some_tensor.device)

tensor([[0.0796, 0.7563, 0.4322, 0.7090],
        [0.5381, 0.8500, 0.0941, 0.4752],
        [0.4227, 0.4377, 0.6341, 0.2194]])
Data type of the tensor torch.float32
Shape of the tensor   torch.Size([3, 4])
Device the tensor is ranning  cpu
