<a href="https://colab.research.google.com/github/al-imran-sonet/Learning_PyTorch/blob/main/PyTorch03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Range of tensors and tensor like

Tensor like helps to make tensor with same dimention of tensor of a given tensor .If we want to make a tensor like A we can use "like " option to make a similar dimention tensor B .

In [1]:
import torch

In [3]:
# use of tuch.range() and get deprecated message ,use torch.arange()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
one_to_ten=torch.arange(1 , 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
one_to_twenty=torch.arange(start=0,end=21,step=2)
one_to_twenty

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
# Creating tensor like
ten_zeros= torch.zeros_like(input=one_to_twenty)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
ten_ones= torch.ones_like(input=one_to_twenty)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])