<a href="https://colab.research.google.com/github/al-imran-sonet/Learning_PyTorch/blob/main/PyTorch00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# prompt: print("hello")

print("hello")

hello


In [6]:
print("hello")

hello


In [7]:
print("what are you doing ")

what are you doing 


In [8]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## first code learning 00


In [9]:
import torch
print(torch.__version__)

2.6.0+cu124


In [10]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to tensor
  We will learn about scaler tensor

  PyTorch tensors are created using torch.Tensor()

  --->> read_about {torch.Tensor()}

  --->> read_about {scaler, vactor , matrix , tensor}

  --->> exercise {creating any dimention of tensor }

In [11]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [13]:
# Get tensor back as python int
scalar.item()

7

In [14]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape


torch.Size([2])

In [17]:
# Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
MATRIX[0]

tensor([7, 8])

In [21]:
# tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,4,5],
                      [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
TENSOR=torch.tensor([])

In [26]:
TENSOR=torch.tensor([[[[1,2,3],
                      [3,4,5],
                      [6,7,8]]]])
TENSOR

tensor([[[[1, 2, 3],
          [3, 4, 5],
          [6, 7, 8]]]])

In [29]:
TENSOR.ndim
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [30]:
TENSOR.ndim


4