<a href="https://colab.research.google.com/github/al-imran-sonet/Learning_PyTorch/blob/main/PyTorch02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Zeros and Ones

Tensor using torch take usualy float data type as default .



In [2]:
import torch

In [8]:
# creating tensor of zeros
zeros=torch.zeros(size=(4,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
random_tensor=torch.rand(size=(4,4))

In [11]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
# creating of tensor of ones
ones=torch.ones(size=(4,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
ones.dtype

torch.float32

In [14]:
random_tensor.dtype

torch.float32