<a href="https://colab.research.google.com/github/al-imran-sonet/Learning_PyTorch/blob/main/Tensor_manipulation_P2_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensor Reshaping, Stacking, Squeezing and Unsqueezing
    *Reshaping -- Reshape a input tensor
    *View -- Return a view of an input tensor of cretain shape but keep the same memory as the original tensor ( it is quit similar to the Reshaping )
    *Stacking -- Combine multiple tensor on top of each other (vstack),side by side (hstack)
    *Squeezing --Remove all '1' dimensions from a tensor
    *Unsqueezing -- add a '1' dimension to a target tensor
    *Permute -- Return a view of the input with dimensions prmuted (swapped) in certain way

-->read about(vstack ,hstack)

In [ ]:
import torch

In [ ]:
# creating tensor
x=torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
#add a extra dimension
x_reshaped=x.reshape(2,5)
x_reshaped,x_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [ ]:
# Changing the view
z=x.view(2,5)
z,z.shape


(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [ ]:
z=x.view(1,10)
z,x.shape
# we can see that reshape and view are kind of similer .
# in view if we change the element of z it will change the element of x also
# That means after use the view they(x and z) are somne kind of connected

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([10]))

In [ ]:
z[:,0]=11
z

tensor([[11,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
# Stack tensor on top of each other
x_stacked=torch.stack([x,x,x,x],dim=1)  # We can change the dimention to make the representation different .but make sure the dimention can support the original tensor
x_stacked


tensor([[11, 11, 11, 11],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [ ]:
# torch.squeeze()  remove all single dimension from a target tensor
x_reshaped

tensor([[11,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [ ]:
x_reshaped.shape

torch.Size([2, 5])

In [ ]:
x_reshaped=x_reshaped.reshape(1,10)
x_reshaped


tensor([[11,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
x_reshaped= x_reshaped.squeeze()
x_reshaped.squeeze()
x_reshaped

tensor([11,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a speciffic dimension
x_reshaped.shape

torch.Size([10])

In [37]:
x_reshaped.unsqueeze(dim=1) # we cant use any dimension we like .
# x_reshaped=x_reshaped.unsqueeze(dim=1)

tensor([[11],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [40]:
# torch.permute() rearrange the dimension of a tensor ina a specified order
x_original =torch.rand(size=(224,224,3)) # hight , width , colour channel
x_permute= x_original.permute(2,0,1) # 0->1,1->2,2->0
x_original.shape,x_permute.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))